#ifndef ASEMANCLIENTMACROS_H
#define ASEMANCLIENTMACROS_H

#define ASM_HIGH_PRIORITY 10000
#define ASM_NORMAL_PRIORITY 1000
#define ASM_LOW_PRIORITY 100
#define ASM_DEFAULT_PRIORITY ASM_NORMAL_PRIORITY

#endif
